### ISSUE TITLE
非编辑器下打包后无法跳转场景

### ISSUE THREAD

**Issue by petergjh** [sunsvip/GF_HybridCLR#3]
进度条满后卡住无法切换下一个场景

**Comment by sunsvip** [comment]
1. 工程默认是热更模式，打开后走进度条是在下载资源和热更代码，如下图可以切换成单机模式/热更新模式；
![image](https://user-images.githubusercontent.com/16739213/224064641-39236ec8-63c2-440b-a2a0-089c83b8344d.png)

2. 如果是热更模式，首次打包应该用Full Build，光标停留在Build按钮有提示。因为Full Build会生成AOT dll到Resources/AotDlls下以供HybridCLR补充泛型元数据；报错的原因应该就是缺少Aot Dll；可以在App Builder界面勾选Debug Mode打包，Debug模式会显示debug窗口，可以看到报错信息
![image](https://user-images.githubusercontent.com/16739213/224066789-70d25cdd-db82-4534-9470-62c620c2dc1d.png)

**Comment by petergjh** [comment]
在Debug Mode下查到原因了,有漏打的AB资源包，导致切换时加载不到对应的预制
