### ISSUE TITLE
我想请问一下 我要如何使用这个框架

### ISSUE THREAD

**Issue by CoderHLei** [sunsvip/GF_HybridCLR#4]
在unityhub中创建项目之后我要如何将框架导入到项目中

**Comment by sunsvip** [comment]
这就是个通用的项目框架模板工程，基于此工程直接写业务逻辑。

**Comment by CoderHLei** [comment]
> 这就是个通用的项目框架模板工程，基于此工程直接写业务逻辑。

直接复制粘贴到unity项目中吗
