### ISSUE TITLE
最新版本似乎在打包时会发生错误

### ISSUE THREAD

**Issue by Daimoo213** [sunsvip/GF_HybridCLR#7]
![提交问题](https://github.com/user-attachments/assets/87dc4c0b-8a97-45bc-9a77-01c8ebd9b476)
打包发生报错在UIExtension.cs中的using UnityEditor.Playables;
改为using UnityEditor后可以正常打包
但直接删除整行似乎不能正常进行打包

**Comment by sunsvip** [comment]
> ![提交问题](https://private-user-images.githubusercontent.com/130738969/358149536-87dc4c0b-8a97-45bc-9a77-01c8ebd9b476.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3Mjk3MTYsIm5iZiI6MTcyMzcyOTQxNiwicGF0aCI6Ii8xMzA3Mzg5NjkvMzU4MTQ5NTM2LTg3ZGM0YzBiLThhOTctNDViYy05YTc3LTAxYzhlYmQ5YjQ3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQxMzQzMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OGQxNDg0ZWEyOWUxNjJmZmJmNzlhOGYxYmVjZmMxNzE1YTNlMDg4MjhiZTMzODBjZTM5NTE1N2Q1ODE1MDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8SWlI8R8fe15ld5eEXCJRMxW9OL4vlxzf4uZueY8QW4) 打包发生报错在UIExtension.cs中的using UnityEditor.Playables; 改为using UnityEditor后可以正常打包 但直接删除整行似乎不能正常进行打包

Runtime脚本误引用编辑器名字名字空间，清除错误引用的名字空间即可
